import Editor from "@monaco-editor/react";

const placeholderVuln = `function withdraw(uint256 amount) external {
    require(balances[msg.sender] >= amount, "Insufficient");
    (bool ok, ) = msg.sender.call{value: amount}("");
    require(ok, "Transfer failed");
    balances[msg.sender] -= amount;
}`;

const placeholderPatch = `function withdraw(uint256 amount) external {
    require(balances[msg.sender] >= amount, "Insufficient");
    balances[msg.sender] -= amount;
    (bool ok, ) = msg.sender.call{value: amount}("");
    require(ok, "Transfer failed");
}`;

export default function Remediation({ data }: { data: any }) {
  const vulnCode = data?.remediation?.original || placeholderVuln;
  const patchCode = data?.remediation?.patch || placeholderPatch;

  return (
    <section className="grid gap-6 lg:grid-cols-[1fr,1fr]">
      <div className="card rounded-3xl p-5">
        <h3 className="text-lg font-semibold">Vulnerable Code</h3>
        <p className="text-xs text-slate-400">
          Highlighted with red diff accents (placeholder).
        </p>
        <div className="mt-4 h-[360px] overflow-hidden rounded-2xl border border-slate-800">
          <Editor
            language="sol"
            value={vulnCode}
            theme="vs-dark"
            options={{
              readOnly: true,
              minimap: { enabled: false },
              fontSize: 13
            }}
          />
        </div>
      </div>
      <div className="card rounded-3xl p-5">
        <h3 className="text-lg font-semibold">Proposed Patch</h3>
        <p className="text-xs text-slate-400">
          Generated by CodeT5 module (placeholder).
        </p>
        <div className="mt-4 h-[360px] overflow-hidden rounded-2xl border border-slate-800">
          <Editor
            language="sol"
            value={patchCode}
            theme="vs-dark"
            options={{
              readOnly: true,
              minimap: { enabled: false },
              fontSize: 13
            }}
          />
        </div>
        <div className="mt-4 rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-xs text-emerald-200">
          Ensure the patch compiles before deploying. Human review remains
          required for production contracts.
        </div>
      </div>
    </section>
  );
}
